apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag
spec:
  selector:
    matchLabels:
      app: rag-llamaindex-wikipedia
  template:
    metadata:
      labels:
        app: rag-llamaindex-wikipedia
    spec:
      containers:
        - name: rag
          image: esara/rag:traceloop
          ports:
            - containerPort: 8501
          env:
            - name: TRACELOOP_API_KEY
              valueFrom:
                secretKeyRef:
                  key: TRACELOOP_API_KEY
                  name: rag-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rag
spec:
  selector:
    app: rag-llamaindex-wikipedia
  ports:
    - name: http
      port: 8501
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rag-secret
data:
  TRACELOOP_API_KEY: "XYZ="